Fixed Initializers are not allowed in ambient contexts.`
Also note that we could have used the skipLibCheck switch in tsconfig.json on the Angular side.

Full error: "ERROR in node_modules/tangy-form/tangy-form-response-model.d.ts:18:17 - error TS1039: Initializers are not allowed in ambient contexts."